/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeToProRouteImport } from './routes/welcome-to-pro'
import { Route as VerifyRecipientRouteImport } from './routes/verify-recipient'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsIntegrationsRouteImport } from './routes/docs/integrations'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsFormsRouteImport } from './routes/docs/forms'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiVerifyRecipientRouteImport } from './routes/api/verify-recipient'
import { Route as ApiBucketsRouteImport } from './routes/api/buckets'
import { Route as ApiApiKeysRouteImport } from './routes/api/api-keys'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AppFormsIndexRouteImport } from './routes/app/forms/index'
import { Route as AppFormsIdRouteImport } from './routes/app/forms/$id'
import { Route as ApiBucketsBucketIdRouteImport } from './routes/api/buckets/$bucketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppFormsIdSubmissionsRouteImport } from './routes/app/forms/$id/submissions'
import { Route as AppFormsIdSettingsRouteImport } from './routes/app/forms/$id/settings'
import { Route as AppFormsIdNotificationsRouteImport } from './routes/app/forms/$id/notifications'
import { Route as AppFormsIdIntegrationsRouteImport } from './routes/app/forms/$id/integrations'
import { Route as AppFormsIdAnalyticsRouteImport } from './routes/app/forms/$id/analytics'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack/callback'
import { Route as ApiIntegrationsSlackAuthorizeRouteImport } from './routes/api/integrations/slack/authorize'
import { Route as ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport } from './routes/api/integrations/google-sheets/spreadsheets'
import { Route as ApiIntegrationsGoogleSheetsDisconnectRouteImport } from './routes/api/integrations/google-sheets/disconnect'
import { Route as ApiIntegrationsGoogleSheetsConfigureRouteImport } from './routes/api/integrations/google-sheets/configure'
import { Route as ApiIntegrationsGoogleSheetsCallbackRouteImport } from './routes/api/integrations/google-sheets/callback'
import { Route as ApiIntegrationsGoogleSheetsAuthorizeRouteImport } from './routes/api/integrations/google-sheets/authorize'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord/callback'
import { Route as ApiIntegrationsDiscordAuthorizeRouteImport } from './routes/api/integrations/discord/authorize'
import { Route as ApiBucketsBucketIdSubmissionsRouteImport } from './routes/api/buckets/$bucketId/submissions'
import { Route as ApiBucketsBucketIdRecipientsRouteImport } from './routes/api/buckets/$bucketId/recipients'
import { Route as ApiBucketsBucketIdDisconnectSlackRouteImport } from './routes/api/buckets/$bucketId/disconnect-slack'
import { Route as ApiBucketsBucketIdDisconnectDiscordRouteImport } from './routes/api/buckets/$bucketId/disconnect-discord'
import { Route as ApiBucketsBucketIdAnalyticsRouteImport } from './routes/api/buckets/$bucketId/analytics'
import { Route as ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport } from './routes/api/buckets/$bucketId/submissions/$submissionId'
import { Route as ApiBucketsBucketIdRecipientsRecipientIdRouteImport } from './routes/api/buckets/$bucketId/recipients/$recipientId'
import { Route as ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRouteImport } from './routes/api/buckets/$bucketId/recipients/$recipientId/resend-verification'

const WelcomeToProRoute = WelcomeToProRouteImport.update({
  id: '/welcome-to-pro',
  path: '/welcome-to-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRecipientRoute = VerifyRecipientRouteImport.update({
  id: '/verify-recipient',
  path: '/verify-recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntegrationsRoute = DocsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFormsRoute = DocsFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiVerifyRecipientRoute = ApiVerifyRecipientRouteImport.update({
  id: '/api/verify-recipient',
  path: '/api/verify-recipient',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBucketsRoute = ApiBucketsRouteImport.update({
  id: '/api/buckets',
  path: '/api/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysRoute = ApiApiKeysRouteImport.update({
  id: '/api/api-keys',
  path: '/api/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiBucketsBucketIdRoute = ApiBucketsBucketIdRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => ApiBucketsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIdSubmissionsRoute = AppFormsIdSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdSettingsRoute = AppFormsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdNotificationsRoute = AppFormsIdNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdIntegrationsRoute = AppFormsIdIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdAnalyticsRoute = AppFormsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackAuthorizeRoute =
  ApiIntegrationsSlackAuthorizeRouteImport.update({
    id: '/api/integrations/slack/authorize',
    path: '/api/integrations/slack/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsSpreadsheetsRoute =
  ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport.update({
    id: '/api/integrations/google-sheets/spreadsheets',
    path: '/api/integrations/google-sheets/spreadsheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsDisconnectRoute =
  ApiIntegrationsGoogleSheetsDisconnectRouteImport.update({
    id: '/api/integrations/google-sheets/disconnect',
    path: '/api/integrations/google-sheets/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsConfigureRoute =
  ApiIntegrationsGoogleSheetsConfigureRouteImport.update({
    id: '/api/integrations/google-sheets/configure',
    path: '/api/integrations/google-sheets/configure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsCallbackRoute =
  ApiIntegrationsGoogleSheetsCallbackRouteImport.update({
    id: '/api/integrations/google-sheets/callback',
    path: '/api/integrations/google-sheets/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsGoogleSheetsAuthorizeRoute =
  ApiIntegrationsGoogleSheetsAuthorizeRouteImport.update({
    id: '/api/integrations/google-sheets/authorize',
    path: '/api/integrations/google-sheets/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordAuthorizeRoute =
  ApiIntegrationsDiscordAuthorizeRouteImport.update({
    id: '/api/integrations/discord/authorize',
    path: '/api/integrations/discord/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBucketsBucketIdSubmissionsRoute =
  ApiBucketsBucketIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdRecipientsRoute =
  ApiBucketsBucketIdRecipientsRouteImport.update({
    id: '/recipients',
    path: '/recipients',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdDisconnectSlackRoute =
  ApiBucketsBucketIdDisconnectSlackRouteImport.update({
    id: '/disconnect-slack',
    path: '/disconnect-slack',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdDisconnectDiscordRoute =
  ApiBucketsBucketIdDisconnectDiscordRouteImport.update({
    id: '/disconnect-discord',
    path: '/disconnect-discord',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdAnalyticsRoute =
  ApiBucketsBucketIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdSubmissionsSubmissionIdRoute =
  ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiBucketsBucketIdSubmissionsRoute,
  } as any)
const ApiBucketsBucketIdRecipientsRecipientIdRoute =
  ApiBucketsBucketIdRecipientsRecipientIdRouteImport.update({
    id: '/$recipientId',
    path: '/$recipientId',
    getParentRoute: () => ApiBucketsBucketIdRecipientsRoute,
  } as any)
const ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute =
  ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRouteImport.update({
    id: '/resend-verification',
    path: '/resend-verification',
    getParentRoute: () => ApiBucketsBucketIdRecipientsRecipientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/disconnect-discord': typeof ApiBucketsBucketIdDisconnectDiscordRoute
  '/api/buckets/$bucketId/disconnect-slack': typeof ApiBucketsBucketIdDisconnectSlackRoute
  '/api/buckets/$bucketId/recipients': typeof ApiBucketsBucketIdRecipientsRouteWithChildren
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/recipients/$recipientId': typeof ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
  '/api/buckets/$bucketId/recipients/$recipientId/resend-verification': typeof ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/disconnect-discord': typeof ApiBucketsBucketIdDisconnectDiscordRoute
  '/api/buckets/$bucketId/disconnect-slack': typeof ApiBucketsBucketIdDisconnectSlackRoute
  '/api/buckets/$bucketId/recipients': typeof ApiBucketsBucketIdRecipientsRouteWithChildren
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/recipients/$recipientId': typeof ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
  '/api/buckets/$bucketId/recipients/$recipientId/resend-verification': typeof ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-recipient': typeof VerifyRecipientRoute
  '/welcome-to-pro': typeof WelcomeToProRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRoute
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/api/verify-recipient': typeof ApiVerifyRecipientRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/app/settings': typeof AppSettingsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/forms': typeof DocsFormsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/integrations': typeof DocsIntegrationsRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms/': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/disconnect-discord': typeof ApiBucketsBucketIdDisconnectDiscordRoute
  '/api/buckets/$bucketId/disconnect-slack': typeof ApiBucketsBucketIdDisconnectSlackRoute
  '/api/buckets/$bucketId/recipients': typeof ApiBucketsBucketIdRecipientsRouteWithChildren
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/api/integrations/discord/authorize': typeof ApiIntegrationsDiscordAuthorizeRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/google-sheets/authorize': typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  '/api/integrations/google-sheets/callback': typeof ApiIntegrationsGoogleSheetsCallbackRoute
  '/api/integrations/google-sheets/configure': typeof ApiIntegrationsGoogleSheetsConfigureRoute
  '/api/integrations/google-sheets/disconnect': typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  '/api/integrations/google-sheets/spreadsheets': typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  '/api/integrations/slack/authorize': typeof ApiIntegrationsSlackAuthorizeRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/integrations': typeof AppFormsIdIntegrationsRoute
  '/app/forms/$id/notifications': typeof AppFormsIdNotificationsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/recipients/$recipientId': typeof ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
  '/api/buckets/$bucketId/recipients/$recipientId/resend-verification': typeof ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/docs/'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/disconnect-discord'
    | '/api/buckets/$bucketId/disconnect-slack'
    | '/api/buckets/$bucketId/recipients'
    | '/api/buckets/$bucketId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/recipients/$recipientId'
    | '/api/buckets/$bucketId/submissions/$submissionId'
    | '/api/buckets/$bucketId/recipients/$recipientId/resend-verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/docs'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/disconnect-discord'
    | '/api/buckets/$bucketId/disconnect-slack'
    | '/api/buckets/$bucketId/recipients'
    | '/api/buckets/$bucketId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/recipients/$recipientId'
    | '/api/buckets/$bucketId/submissions/$submissionId'
    | '/api/buckets/$bucketId/recipients/$recipientId/resend-verification'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/verify-email'
    | '/verify-recipient'
    | '/welcome-to-pro'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/api/verify-recipient'
    | '/app/analytics'
    | '/app/api-keys'
    | '/app/settings'
    | '/docs/api'
    | '/docs/forms'
    | '/docs/getting-started'
    | '/docs/integrations'
    | '/docs/'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms/'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/disconnect-discord'
    | '/api/buckets/$bucketId/disconnect-slack'
    | '/api/buckets/$bucketId/recipients'
    | '/api/buckets/$bucketId/submissions'
    | '/api/integrations/discord/authorize'
    | '/api/integrations/discord/callback'
    | '/api/integrations/google-sheets/authorize'
    | '/api/integrations/google-sheets/callback'
    | '/api/integrations/google-sheets/configure'
    | '/api/integrations/google-sheets/disconnect'
    | '/api/integrations/google-sheets/spreadsheets'
    | '/api/integrations/slack/authorize'
    | '/api/integrations/slack/callback'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/integrations'
    | '/app/forms/$id/notifications'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/recipients/$recipientId'
    | '/api/buckets/$bucketId/submissions/$submissionId'
    | '/api/buckets/$bucketId/recipients/$recipientId/resend-verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyRecipientRoute: typeof VerifyRecipientRoute
  WelcomeToProRoute: typeof WelcomeToProRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiApiKeysRoute: typeof ApiApiKeysRoute
  ApiBucketsRoute: typeof ApiBucketsRouteWithChildren
  ApiVerifyRecipientRoute: typeof ApiVerifyRecipientRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiIntegrationsDiscordAuthorizeRoute: typeof ApiIntegrationsDiscordAuthorizeRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsGoogleSheetsAuthorizeRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRoute
  ApiIntegrationsGoogleSheetsCallbackRoute: typeof ApiIntegrationsGoogleSheetsCallbackRoute
  ApiIntegrationsGoogleSheetsConfigureRoute: typeof ApiIntegrationsGoogleSheetsConfigureRoute
  ApiIntegrationsGoogleSheetsDisconnectRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRoute
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRoute
  ApiIntegrationsSlackAuthorizeRoute: typeof ApiIntegrationsSlackAuthorizeRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome-to-pro': {
      id: '/welcome-to-pro'
      path: '/welcome-to-pro'
      fullPath: '/welcome-to-pro'
      preLoaderRoute: typeof WelcomeToProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-recipient': {
      id: '/verify-recipient'
      path: '/verify-recipient'
      fullPath: '/verify-recipient'
      preLoaderRoute: typeof VerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/integrations': {
      id: '/docs/integrations'
      path: '/integrations'
      fullPath: '/docs/integrations'
      preLoaderRoute: typeof DocsIntegrationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/forms': {
      id: '/docs/forms'
      path: '/forms'
      fullPath: '/docs/forms'
      preLoaderRoute: typeof DocsFormsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/verify-recipient': {
      id: '/api/verify-recipient'
      path: '/api/verify-recipient'
      fullPath: '/api/verify-recipient'
      preLoaderRoute: typeof ApiVerifyRecipientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buckets': {
      id: '/api/buckets'
      path: '/api/buckets'
      fullPath: '/api/buckets'
      preLoaderRoute: typeof ApiBucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys': {
      id: '/api/api-keys'
      path: '/api/api-keys'
      fullPath: '/api/api-keys'
      preLoaderRoute: typeof ApiApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms/$id': {
      id: '/app/forms/$id'
      path: '/forms/$id'
      fullPath: '/app/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/buckets/$bucketId': {
      id: '/api/buckets/$bucketId'
      path: '/$bucketId'
      fullPath: '/api/buckets/$bucketId'
      preLoaderRoute: typeof ApiBucketsBucketIdRouteImport
      parentRoute: typeof ApiBucketsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forms/$id/submissions': {
      id: '/app/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/app/forms/$id/submissions'
      preLoaderRoute: typeof AppFormsIdSubmissionsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/settings': {
      id: '/app/forms/$id/settings'
      path: '/settings'
      fullPath: '/app/forms/$id/settings'
      preLoaderRoute: typeof AppFormsIdSettingsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/notifications': {
      id: '/app/forms/$id/notifications'
      path: '/notifications'
      fullPath: '/app/forms/$id/notifications'
      preLoaderRoute: typeof AppFormsIdNotificationsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/integrations': {
      id: '/app/forms/$id/integrations'
      path: '/integrations'
      fullPath: '/app/forms/$id/integrations'
      preLoaderRoute: typeof AppFormsIdIntegrationsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/analytics': {
      id: '/app/forms/$id/analytics'
      path: '/analytics'
      fullPath: '/app/forms/$id/analytics'
      preLoaderRoute: typeof AppFormsIdAnalyticsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/authorize': {
      id: '/api/integrations/slack/authorize'
      path: '/api/integrations/slack/authorize'
      fullPath: '/api/integrations/slack/authorize'
      preLoaderRoute: typeof ApiIntegrationsSlackAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/spreadsheets': {
      id: '/api/integrations/google-sheets/spreadsheets'
      path: '/api/integrations/google-sheets/spreadsheets'
      fullPath: '/api/integrations/google-sheets/spreadsheets'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsSpreadsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/disconnect': {
      id: '/api/integrations/google-sheets/disconnect'
      path: '/api/integrations/google-sheets/disconnect'
      fullPath: '/api/integrations/google-sheets/disconnect'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/configure': {
      id: '/api/integrations/google-sheets/configure'
      path: '/api/integrations/google-sheets/configure'
      fullPath: '/api/integrations/google-sheets/configure'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/callback': {
      id: '/api/integrations/google-sheets/callback'
      path: '/api/integrations/google-sheets/callback'
      fullPath: '/api/integrations/google-sheets/callback'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/google-sheets/authorize': {
      id: '/api/integrations/google-sheets/authorize'
      path: '/api/integrations/google-sheets/authorize'
      fullPath: '/api/integrations/google-sheets/authorize'
      preLoaderRoute: typeof ApiIntegrationsGoogleSheetsAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/authorize': {
      id: '/api/integrations/discord/authorize'
      path: '/api/integrations/discord/authorize'
      fullPath: '/api/integrations/discord/authorize'
      preLoaderRoute: typeof ApiIntegrationsDiscordAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buckets/$bucketId/submissions': {
      id: '/api/buckets/$bucketId/submissions'
      path: '/submissions'
      fullPath: '/api/buckets/$bucketId/submissions'
      preLoaderRoute: typeof ApiBucketsBucketIdSubmissionsRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/recipients': {
      id: '/api/buckets/$bucketId/recipients'
      path: '/recipients'
      fullPath: '/api/buckets/$bucketId/recipients'
      preLoaderRoute: typeof ApiBucketsBucketIdRecipientsRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/disconnect-slack': {
      id: '/api/buckets/$bucketId/disconnect-slack'
      path: '/disconnect-slack'
      fullPath: '/api/buckets/$bucketId/disconnect-slack'
      preLoaderRoute: typeof ApiBucketsBucketIdDisconnectSlackRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/disconnect-discord': {
      id: '/api/buckets/$bucketId/disconnect-discord'
      path: '/disconnect-discord'
      fullPath: '/api/buckets/$bucketId/disconnect-discord'
      preLoaderRoute: typeof ApiBucketsBucketIdDisconnectDiscordRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/analytics': {
      id: '/api/buckets/$bucketId/analytics'
      path: '/analytics'
      fullPath: '/api/buckets/$bucketId/analytics'
      preLoaderRoute: typeof ApiBucketsBucketIdAnalyticsRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/submissions/$submissionId': {
      id: '/api/buckets/$bucketId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/buckets/$bucketId/submissions/$submissionId'
      preLoaderRoute: typeof ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiBucketsBucketIdSubmissionsRoute
    }
    '/api/buckets/$bucketId/recipients/$recipientId': {
      id: '/api/buckets/$bucketId/recipients/$recipientId'
      path: '/$recipientId'
      fullPath: '/api/buckets/$bucketId/recipients/$recipientId'
      preLoaderRoute: typeof ApiBucketsBucketIdRecipientsRecipientIdRouteImport
      parentRoute: typeof ApiBucketsBucketIdRecipientsRoute
    }
    '/api/buckets/$bucketId/recipients/$recipientId/resend-verification': {
      id: '/api/buckets/$bucketId/recipients/$recipientId/resend-verification'
      path: '/resend-verification'
      fullPath: '/api/buckets/$bucketId/recipients/$recipientId/resend-verification'
      preLoaderRoute: typeof ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRouteImport
      parentRoute: typeof ApiBucketsBucketIdRecipientsRecipientIdRoute
    }
  }
}

interface AppFormsIdRouteChildren {
  AppFormsIdAnalyticsRoute: typeof AppFormsIdAnalyticsRoute
  AppFormsIdIntegrationsRoute: typeof AppFormsIdIntegrationsRoute
  AppFormsIdNotificationsRoute: typeof AppFormsIdNotificationsRoute
  AppFormsIdSettingsRoute: typeof AppFormsIdSettingsRoute
  AppFormsIdSubmissionsRoute: typeof AppFormsIdSubmissionsRoute
}

const AppFormsIdRouteChildren: AppFormsIdRouteChildren = {
  AppFormsIdAnalyticsRoute: AppFormsIdAnalyticsRoute,
  AppFormsIdIntegrationsRoute: AppFormsIdIntegrationsRoute,
  AppFormsIdNotificationsRoute: AppFormsIdNotificationsRoute,
  AppFormsIdSettingsRoute: AppFormsIdSettingsRoute,
  AppFormsIdSubmissionsRoute: AppFormsIdSubmissionsRoute,
}

const AppFormsIdRouteWithChildren = AppFormsIdRoute._addFileChildren(
  AppFormsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppFormsIdRoute: typeof AppFormsIdRouteWithChildren
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppFormsIdRoute: AppFormsIdRouteWithChildren,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsFormsRoute: typeof DocsFormsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsIntegrationsRoute: typeof DocsIntegrationsRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsFormsRoute: DocsFormsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsIntegrationsRoute: DocsIntegrationsRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiBucketsBucketIdRecipientsRecipientIdRouteChildren {
  ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute: typeof ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute
}

const ApiBucketsBucketIdRecipientsRecipientIdRouteChildren: ApiBucketsBucketIdRecipientsRecipientIdRouteChildren =
  {
    ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute:
      ApiBucketsBucketIdRecipientsRecipientIdResendVerificationRoute,
  }

const ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren =
  ApiBucketsBucketIdRecipientsRecipientIdRoute._addFileChildren(
    ApiBucketsBucketIdRecipientsRecipientIdRouteChildren,
  )

interface ApiBucketsBucketIdRecipientsRouteChildren {
  ApiBucketsBucketIdRecipientsRecipientIdRoute: typeof ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren
}

const ApiBucketsBucketIdRecipientsRouteChildren: ApiBucketsBucketIdRecipientsRouteChildren =
  {
    ApiBucketsBucketIdRecipientsRecipientIdRoute:
      ApiBucketsBucketIdRecipientsRecipientIdRouteWithChildren,
  }

const ApiBucketsBucketIdRecipientsRouteWithChildren =
  ApiBucketsBucketIdRecipientsRoute._addFileChildren(
    ApiBucketsBucketIdRecipientsRouteChildren,
  )

interface ApiBucketsBucketIdSubmissionsRouteChildren {
  ApiBucketsBucketIdSubmissionsSubmissionIdRoute: typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
}

const ApiBucketsBucketIdSubmissionsRouteChildren: ApiBucketsBucketIdSubmissionsRouteChildren =
  {
    ApiBucketsBucketIdSubmissionsSubmissionIdRoute:
      ApiBucketsBucketIdSubmissionsSubmissionIdRoute,
  }

const ApiBucketsBucketIdSubmissionsRouteWithChildren =
  ApiBucketsBucketIdSubmissionsRoute._addFileChildren(
    ApiBucketsBucketIdSubmissionsRouteChildren,
  )

interface ApiBucketsBucketIdRouteChildren {
  ApiBucketsBucketIdAnalyticsRoute: typeof ApiBucketsBucketIdAnalyticsRoute
  ApiBucketsBucketIdDisconnectDiscordRoute: typeof ApiBucketsBucketIdDisconnectDiscordRoute
  ApiBucketsBucketIdDisconnectSlackRoute: typeof ApiBucketsBucketIdDisconnectSlackRoute
  ApiBucketsBucketIdRecipientsRoute: typeof ApiBucketsBucketIdRecipientsRouteWithChildren
  ApiBucketsBucketIdSubmissionsRoute: typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
}

const ApiBucketsBucketIdRouteChildren: ApiBucketsBucketIdRouteChildren = {
  ApiBucketsBucketIdAnalyticsRoute: ApiBucketsBucketIdAnalyticsRoute,
  ApiBucketsBucketIdDisconnectDiscordRoute:
    ApiBucketsBucketIdDisconnectDiscordRoute,
  ApiBucketsBucketIdDisconnectSlackRoute:
    ApiBucketsBucketIdDisconnectSlackRoute,
  ApiBucketsBucketIdRecipientsRoute:
    ApiBucketsBucketIdRecipientsRouteWithChildren,
  ApiBucketsBucketIdSubmissionsRoute:
    ApiBucketsBucketIdSubmissionsRouteWithChildren,
}

const ApiBucketsBucketIdRouteWithChildren =
  ApiBucketsBucketIdRoute._addFileChildren(ApiBucketsBucketIdRouteChildren)

interface ApiBucketsRouteChildren {
  ApiBucketsBucketIdRoute: typeof ApiBucketsBucketIdRouteWithChildren
}

const ApiBucketsRouteChildren: ApiBucketsRouteChildren = {
  ApiBucketsBucketIdRoute: ApiBucketsBucketIdRouteWithChildren,
}

const ApiBucketsRouteWithChildren = ApiBucketsRoute._addFileChildren(
  ApiBucketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyRecipientRoute: VerifyRecipientRoute,
  WelcomeToProRoute: WelcomeToProRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiApiKeysRoute: ApiApiKeysRoute,
  ApiBucketsRoute: ApiBucketsRouteWithChildren,
  ApiVerifyRecipientRoute: ApiVerifyRecipientRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiIntegrationsDiscordAuthorizeRoute: ApiIntegrationsDiscordAuthorizeRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsGoogleSheetsAuthorizeRoute:
    ApiIntegrationsGoogleSheetsAuthorizeRoute,
  ApiIntegrationsGoogleSheetsCallbackRoute:
    ApiIntegrationsGoogleSheetsCallbackRoute,
  ApiIntegrationsGoogleSheetsConfigureRoute:
    ApiIntegrationsGoogleSheetsConfigureRoute,
  ApiIntegrationsGoogleSheetsDisconnectRoute:
    ApiIntegrationsGoogleSheetsDisconnectRoute,
  ApiIntegrationsGoogleSheetsSpreadsheetsRoute:
    ApiIntegrationsGoogleSheetsSpreadsheetsRoute,
  ApiIntegrationsSlackAuthorizeRoute: ApiIntegrationsSlackAuthorizeRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
