/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppApiKeysRouteImport } from './routes/app/api-keys'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as ApiBucketsRouteImport } from './routes/api/buckets'
import { Route as ApiApiKeysRouteImport } from './routes/api/api-keys'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AppFormsIndexRouteImport } from './routes/app/forms/index'
import { Route as AppFormsIdRouteImport } from './routes/app/forms/$id'
import { Route as ApiBucketsBucketIdRouteImport } from './routes/api/buckets/$bucketId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiApiKeysKeyIdRouteImport } from './routes/api/api-keys/$keyId'
import { Route as AppFormsIdSubmissionsRouteImport } from './routes/app/forms/$id/submissions'
import { Route as AppFormsIdSettingsRouteImport } from './routes/app/forms/$id/settings'
import { Route as AppFormsIdAnalyticsRouteImport } from './routes/app/forms/$id/analytics'
import { Route as ApiBucketsBucketIdSubmissionsRouteImport } from './routes/api/buckets/$bucketId/submissions'
import { Route as ApiBucketsBucketIdAnalyticsRouteImport } from './routes/api/buckets/$bucketId/analytics'
import { Route as ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport } from './routes/api/buckets/$bucketId/submissions/$submissionId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiBucketsRoute = ApiBucketsRouteImport.update({
  id: '/api/buckets',
  path: '/api/buckets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysRoute = ApiApiKeysRouteImport.update({
  id: '/api/api-keys',
  path: '/api/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFormsIndexRoute = AppFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFormsIdRoute = AppFormsIdRouteImport.update({
  id: '/forms/$id',
  path: '/forms/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiBucketsBucketIdRoute = ApiBucketsBucketIdRouteImport.update({
  id: '/$bucketId',
  path: '/$bucketId',
  getParentRoute: () => ApiBucketsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApiKeysKeyIdRoute = ApiApiKeysKeyIdRouteImport.update({
  id: '/$keyId',
  path: '/$keyId',
  getParentRoute: () => ApiApiKeysRoute,
} as any)
const AppFormsIdSubmissionsRoute = AppFormsIdSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdSettingsRoute = AppFormsIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const AppFormsIdAnalyticsRoute = AppFormsIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppFormsIdRoute,
} as any)
const ApiBucketsBucketIdSubmissionsRoute =
  ApiBucketsBucketIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdAnalyticsRoute =
  ApiBucketsBucketIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => ApiBucketsBucketIdRoute,
  } as any)
const ApiBucketsBucketIdSubmissionsSubmissionIdRoute =
  ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => ApiBucketsBucketIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRouteWithChildren
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/api/api-keys/$keyId': typeof ApiApiKeysKeyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRouteWithChildren
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/api/api-keys/$keyId': typeof ApiApiKeysKeyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/api-keys': typeof ApiApiKeysRouteWithChildren
  '/api/buckets': typeof ApiBucketsRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/api-keys': typeof AppApiKeysRoute
  '/api/api-keys/$keyId': typeof ApiApiKeysKeyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/buckets/$bucketId': typeof ApiBucketsBucketIdRouteWithChildren
  '/app/forms/$id': typeof AppFormsIdRouteWithChildren
  '/app/forms/': typeof AppFormsIndexRoute
  '/api/buckets/$bucketId/analytics': typeof ApiBucketsBucketIdAnalyticsRoute
  '/api/buckets/$bucketId/submissions': typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
  '/app/forms/$id/analytics': typeof AppFormsIdAnalyticsRoute
  '/app/forms/$id/settings': typeof AppFormsIdSettingsRoute
  '/app/forms/$id/submissions': typeof AppFormsIdSubmissionsRoute
  '/api/buckets/$bucketId/submissions/$submissionId': typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/app/analytics'
    | '/app/api-keys'
    | '/api/api-keys/$keyId'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/submissions'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/app/analytics'
    | '/app/api-keys'
    | '/api/api-keys/$keyId'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/submissions'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/api/analytics'
    | '/api/api-keys'
    | '/api/buckets'
    | '/app/analytics'
    | '/app/api-keys'
    | '/api/api-keys/$keyId'
    | '/api/auth/$'
    | '/api/buckets/$bucketId'
    | '/app/forms/$id'
    | '/app/forms/'
    | '/api/buckets/$bucketId/analytics'
    | '/api/buckets/$bucketId/submissions'
    | '/app/forms/$id/analytics'
    | '/app/forms/$id/settings'
    | '/app/forms/$id/submissions'
    | '/api/buckets/$bucketId/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiApiKeysRoute: typeof ApiApiKeysRouteWithChildren
  ApiBucketsRoute: typeof ApiBucketsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/api-keys': {
      id: '/app/api-keys'
      path: '/api-keys'
      fullPath: '/app/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/buckets': {
      id: '/api/buckets'
      path: '/api/buckets'
      fullPath: '/api/buckets'
      preLoaderRoute: typeof ApiBucketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys': {
      id: '/api/api-keys'
      path: '/api/api-keys'
      fullPath: '/api/api-keys'
      preLoaderRoute: typeof ApiApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/forms/': {
      id: '/app/forms/'
      path: '/forms'
      fullPath: '/app/forms'
      preLoaderRoute: typeof AppFormsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forms/$id': {
      id: '/app/forms/$id'
      path: '/forms/$id'
      fullPath: '/app/forms/$id'
      preLoaderRoute: typeof AppFormsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/buckets/$bucketId': {
      id: '/api/buckets/$bucketId'
      path: '/$bucketId'
      fullPath: '/api/buckets/$bucketId'
      preLoaderRoute: typeof ApiBucketsBucketIdRouteImport
      parentRoute: typeof ApiBucketsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/api-keys/$keyId': {
      id: '/api/api-keys/$keyId'
      path: '/$keyId'
      fullPath: '/api/api-keys/$keyId'
      preLoaderRoute: typeof ApiApiKeysKeyIdRouteImport
      parentRoute: typeof ApiApiKeysRoute
    }
    '/app/forms/$id/submissions': {
      id: '/app/forms/$id/submissions'
      path: '/submissions'
      fullPath: '/app/forms/$id/submissions'
      preLoaderRoute: typeof AppFormsIdSubmissionsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/settings': {
      id: '/app/forms/$id/settings'
      path: '/settings'
      fullPath: '/app/forms/$id/settings'
      preLoaderRoute: typeof AppFormsIdSettingsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/app/forms/$id/analytics': {
      id: '/app/forms/$id/analytics'
      path: '/analytics'
      fullPath: '/app/forms/$id/analytics'
      preLoaderRoute: typeof AppFormsIdAnalyticsRouteImport
      parentRoute: typeof AppFormsIdRoute
    }
    '/api/buckets/$bucketId/submissions': {
      id: '/api/buckets/$bucketId/submissions'
      path: '/submissions'
      fullPath: '/api/buckets/$bucketId/submissions'
      preLoaderRoute: typeof ApiBucketsBucketIdSubmissionsRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/analytics': {
      id: '/api/buckets/$bucketId/analytics'
      path: '/analytics'
      fullPath: '/api/buckets/$bucketId/analytics'
      preLoaderRoute: typeof ApiBucketsBucketIdAnalyticsRouteImport
      parentRoute: typeof ApiBucketsBucketIdRoute
    }
    '/api/buckets/$bucketId/submissions/$submissionId': {
      id: '/api/buckets/$bucketId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/api/buckets/$bucketId/submissions/$submissionId'
      preLoaderRoute: typeof ApiBucketsBucketIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof ApiBucketsBucketIdSubmissionsRoute
    }
  }
}

interface AppFormsIdRouteChildren {
  AppFormsIdAnalyticsRoute: typeof AppFormsIdAnalyticsRoute
  AppFormsIdSettingsRoute: typeof AppFormsIdSettingsRoute
  AppFormsIdSubmissionsRoute: typeof AppFormsIdSubmissionsRoute
}

const AppFormsIdRouteChildren: AppFormsIdRouteChildren = {
  AppFormsIdAnalyticsRoute: AppFormsIdAnalyticsRoute,
  AppFormsIdSettingsRoute: AppFormsIdSettingsRoute,
  AppFormsIdSubmissionsRoute: AppFormsIdSubmissionsRoute,
}

const AppFormsIdRouteWithChildren = AppFormsIdRoute._addFileChildren(
  AppFormsIdRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppFormsIdRoute: typeof AppFormsIdRouteWithChildren
  AppFormsIndexRoute: typeof AppFormsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppFormsIdRoute: AppFormsIdRouteWithChildren,
  AppFormsIndexRoute: AppFormsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiApiKeysRouteChildren {
  ApiApiKeysKeyIdRoute: typeof ApiApiKeysKeyIdRoute
}

const ApiApiKeysRouteChildren: ApiApiKeysRouteChildren = {
  ApiApiKeysKeyIdRoute: ApiApiKeysKeyIdRoute,
}

const ApiApiKeysRouteWithChildren = ApiApiKeysRoute._addFileChildren(
  ApiApiKeysRouteChildren,
)

interface ApiBucketsBucketIdSubmissionsRouteChildren {
  ApiBucketsBucketIdSubmissionsSubmissionIdRoute: typeof ApiBucketsBucketIdSubmissionsSubmissionIdRoute
}

const ApiBucketsBucketIdSubmissionsRouteChildren: ApiBucketsBucketIdSubmissionsRouteChildren =
  {
    ApiBucketsBucketIdSubmissionsSubmissionIdRoute:
      ApiBucketsBucketIdSubmissionsSubmissionIdRoute,
  }

const ApiBucketsBucketIdSubmissionsRouteWithChildren =
  ApiBucketsBucketIdSubmissionsRoute._addFileChildren(
    ApiBucketsBucketIdSubmissionsRouteChildren,
  )

interface ApiBucketsBucketIdRouteChildren {
  ApiBucketsBucketIdAnalyticsRoute: typeof ApiBucketsBucketIdAnalyticsRoute
  ApiBucketsBucketIdSubmissionsRoute: typeof ApiBucketsBucketIdSubmissionsRouteWithChildren
}

const ApiBucketsBucketIdRouteChildren: ApiBucketsBucketIdRouteChildren = {
  ApiBucketsBucketIdAnalyticsRoute: ApiBucketsBucketIdAnalyticsRoute,
  ApiBucketsBucketIdSubmissionsRoute:
    ApiBucketsBucketIdSubmissionsRouteWithChildren,
}

const ApiBucketsBucketIdRouteWithChildren =
  ApiBucketsBucketIdRoute._addFileChildren(ApiBucketsBucketIdRouteChildren)

interface ApiBucketsRouteChildren {
  ApiBucketsBucketIdRoute: typeof ApiBucketsBucketIdRouteWithChildren
}

const ApiBucketsRouteChildren: ApiBucketsRouteChildren = {
  ApiBucketsBucketIdRoute: ApiBucketsBucketIdRouteWithChildren,
}

const ApiBucketsRouteWithChildren = ApiBucketsRoute._addFileChildren(
  ApiBucketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiApiKeysRoute: ApiApiKeysRouteWithChildren,
  ApiBucketsRoute: ApiBucketsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
